twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_version: '1.2.6'
        app_settings: '@App\Services\ApplicationSettings'
        seo_service: '@App\Services\SeoService'
        routing_service: '@App\Services\RoutingService'
        app_languages: ['en','fr','de']