<?php

namespace AppBundle\Repository;
use AppBundle\AppBundle;
use AppBundle\Entity\User;
use AppBundle\Entity\UserAgency;
use AppBundle\Entity\VehiclePrice;
use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAllGranted(User $user,$returnQuery = false)
    {

        if ($user->hasRole('ROLE_ADMIN')){
            $q = $this->createQueryBuilder('p')
                ;
            if ($returnQuery){
                return $q;
            }
            return $q->getQuery()->getResult();
        }

        $q = $this->createQueryBuilder('p')
            ->join("p.agency","a")
            ->where('a.user = :user')
            ->setParameter('user', $user);

        if ($returnQuery){
            return $q;
        }
        return $q->getQuery()->getResult();
    }
}