<?php

namespace App\Repository;
use App\Entity\User;
use App\Entity\UserAgency;
use App\Entity\VehiclePrice;
use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyRepository extends EntityRepository
{
    public function findAllGranted(User $user,$returnQuery = false)
    {
        if ($user->hasRole('ROLE_ADMIN')){
            $q = $this->createQueryBuilder('a')
                ;
            if ($returnQuery){
                return $q;
            }
            return $q->getQuery()->getResult();
        }

        $q = $this->createQueryBuilder('a')
            ->join("a.users","uc")
            ->where('uc.user = :user')
            ->andWhere('uc.agency = a')
            ->setParameter('user', $user)
            ;
        if ($returnQuery){
            return $q;
        }
        return $q->getQuery()->getResult();
    }

    /**
     * Toutes les agences avec leur nombre d'excursions, en une seule
     * requête (évite un COUNT par agence dans le template admin).
     *
     * @return array<int, array{0: \App\Entity\Agency, productCount: int}>
     */
    public function findAllWithProductCounts(): array
    {
        return $this->createQueryBuilder('a')
            ->select('a', 'COUNT(p.productId) as productCount')
            ->leftJoin('a.products', 'p')
            ->groupBy('a.id')
            ->orderBy('a.dateCreate', 'DESC')
            ->getQuery()
            ->getResult();
    }
}